EXPERIMENT:
  NAME: ""
  TAG: "Tech_KD,res32x4,res8x4"
  PROJECT: "cifar100_baselines"
DISTILLER:
  TYPE: "TECH_KD"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
  CHILD1: "resnet32x4"
  CHILD2: "resnet32x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05 #0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"